version: "3"
services:
  mymonogdb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  BooksMongodb:
    image: BooksMongodb:1.0
    container_name: BooksMongodb
    ports:
      - 8080:8080
    links:
        -mymongodb
